galacean/galacean.github.io

- 0.1/manual/zh-cn/component/ray.md
> doc: fix raycast doc error

- 0.1/manual/zh-cn/README.md
- 0.2/manual/zh-cn/README.md
> fix: api link

- blog/image-decode-in-webgl.zh-CN.md
- blog/v0.3-release.zh-CN.md
> fix: docs img link error

- docs/miniprogram.zh-CN.md
- src/components/Content/MainContent.tsx
initial version for mini program
> Add Miniprogram Docs

- docs/install.zh-CN.md
Removed the tween library but did not update the description
> fix: image url error

- docs/miniprogram.zh-CN.md
Add a method to use Oasis in a existing miniprogram project.
> Update Miniprogram Docs

- blog/v0.4-release.zh-CN.md
> update:upload blog

- docs/artist-animation-clip.zh-CN.md
- docs/artist-unlit.zh-CN.md
- docs/gltf.zh-CN.md
- docs/material.zh-CN.md
- docs/model.zh-CN.md
- docs/ray.zh-CN.md
- docs/resource-manager.zh-CN.md
* add gltf manual `gltf-cn`
* rename `GLTF` -> `glTF`
* add some link
> Doc: add gltf manual

- src/components/Playground/Codepen.tsx
- src/components/typedoc/Item.tsx
- fix: Codepen preview link error
- fix: typedoc native api 404 link
> fix two small bugs

- docs/instructions-for-designers-on-lottie.zh-CN.md
lottie的设计师向文档，如有格式调整或者修改，麻烦帮忙校正
> doc:04 instructions on lottie

- gatsby-config.js
> fix:playgound link err

- docs/editor-mars.zh-CN.md
- docs/editor-sprite-mask.zh-CN.md
- docs/editor-sprite-renderer.zh-CN.md
- docs/editor-sprite.zh-CN.md
- docs/sprite.zh-CN.md
- Sprite
- Mars
- SpriteRenderer
- SpriteMask
> doc: add doc for 2d

- docs/editor-camera.zh-CN.md
- docs/editor-texture.zh-CN.md
Add editor texture and camera manual.
> feat: add editor texture and camera manual

- docs/editor-inspector.zh-CN.md
- docs/editor-project.zh-CN.md
> feat: editor inspector & project doc

- docs/editor-assets-panel.zh-CN.md
Add the doc about Assets Panel.
For #110.
> docs(editor): add assets panel

- docs/editor-viewport.zh-CN.md
- Add editor viewport documention
> Add Editor Viewport Documention

- docs/texture.zh-CN.md
- playground/filter-mode.ts
- playground/shader-water.ts
- playground/texture-aniso.ts
* fix #104 
* add anisoLevel demo #88 
* add link in doc
> [Playground] add texture anisoLevel demo

- docs/light.zh-CN.md
- playground/ambient-light.ts
* add ambient light demo  https://github.com/oasis-engine/oasis-engine.github.io/issues/86
* add link in doc
> [Playground] add ambient light demo

- docs/light.zh-CN.md
- playground/light-type.ts
- playground/shadow.ts
* [Light] Directional Light #85 
* [Light] Point Light #84 
* [Light] Spot Light #148 
* [Docs] add playground in docs link https://github.com/oasis-engine/oasis-engine.github.io/pull/146 #122
> [Playground]: add light basic playground

- playground/texture-mipmap.ts
> [playground]: add texture-mipmap demo

- docs/framebuffer-picker.zh-CN.md
- docs/gltf.zh-CN.md
- docs/light.zh-CN.md
- docs/material.zh-CN.md
- docs/texture.zh-CN.md
- playground/framebuffer-picker.ts
* light #122 
* texture #134 
* material #135 
* gltf #136 
* framebuffer-picker #140
> Perf: engine docs enhancement

- playground/render-target.ts
> [Playground]: Camera Render Target

- docs/scene.zh-CN.md
- playground/background.ts
Add background docs and playground for [background texture feature](https://github.com/oasis-engine/engine/pull/427)
> docs: add background doc and playground

- playground/.dev/vite.config.js
- playground/animation-cross-fade.ts
fix playground: animation-cross-fade
> fix: animation-cross-fade

- docs/canvas.md
- docs/canvas.zh-CN.md
- docs/lottie.md
- docs/lottie.zh-CN.md
- docs/particle-renderer.md
- docs/particle-renderer.zh-CN.md
- docs/scene.md
- src/components/home/Spine.tsx
Includes docs：
- canvas
- Scene
- Particle System
> docs: Englishization

- docs/script.md
> feat: 英文化脚本文档

- docs/first-script.md
> feat: 英文化第一个脚本文档

- docs/stats.md
- docs/stats.zh-CN.md
- src/components/typedoc/index.less
- src/pages/examples.less
- src/pages/examples.tsx
- feat: add example search
- docs: update engine stats doc
- fix: typedoc nav height bug
> Add example search

- docs/script.md
- docs/script.zh-CN.md
> feat: update script flowchart

- docs/script.md
> feat: update script flowchart #270

- docs/script.md
> fix fontsize

- docs/editor-animator.zh-CN.md
- docs/editor-component-gltf.zh-CN.md
- docs/editor-component-spine.zh-CN.md
- docs/editor-lottie.zh-CN.md
- docs/editor-mars.zh-CN.md
- docs/instructions-for-designers-on-lottie.zh-CN.md
Add animator editor document & fix lottie document image
> Add animator editor document & fix lottie document image

- playground/background.ts
Initing scene background use texture.
> Fix Init Error

- blog/v0.4-release.zh-CN.md
- docs/animator.md
- docs/artist-animation-clip.md
- docs/artist-animation-clip.zh-CN.md
- docs/artist-unlit.zh-CN.md
- docs/editor-animator.zh-CN.md
- docs/editor-asset-store.zh-CN.md
- docs/editor-component-gltf.zh-CN.md
- docs/editor-component-spine.zh-CN.md
- docs/editor-menu.zh-CN.md
- docs/editor-resource-spine.zh-CN.md
- docs/first-game.md
- docs/first-game.zh-CN.md
- docs/material.zh-CN.md
- docs/model.md
- docs/model.zh-CN.md
- docs/sprite-atlas.md
- docs/sprite-atlas.zh-CN.md
- playground/flappy-bird.ts
- playground/sprite-flip.ts
fix:
Picture cannot be displayed
Misspelled word
> fix: doc err

- playground/video-background.ts
* https://github.com/oasis-engine/engine/issues/324
> [Scene] video background

- playground/primitive-mesh.ts
add capsule in primitive mesh example, and adjust in-between distance
> feature: add capsule in primitive mesh

- docs/primitive-mesh.md
- docs/primitive-mesh.zh-CN.md
> feature: add capsule in doc

- docs/collider.md
- docs/collider.zh-CN.md
- docs/ray.md
- docs/ray.zh-CN.md
- playground/lite-collision-detection.ts
- playground/lite-raycast.ts
- src/components/typedoc/Source.tsx
- Update physics docs
- Fix: https://github.com/oasis-engine/oasis-engine.github.io/issues/306
> Update physics docs

- docs/lottie.md
- docs/lottie.zh-CN.md
- gatsby/onCreateNode.js
- package.json
- playground/lottie-3d-rotation.ts
- playground/lottie-clips.ts
- siteconfig.json
- update lottie docs
- fix: remark-mdx version problem
> Update lottie docs

- src/pages/gltf-viewer.tsx
support loading relative file such as "textures/test.png"
> fix: compatible with relative path

- playground/.dev/template/iframe.ejs
- src/pages/gltf-viewer.less
- src/pages/gltf-viewer.tsx
> feat: add upload button on gltf-viewer

- playground/outline.ts
use script instead of renderpass
> Refactor: use script in outline

- src/pages/gltf-viewer.tsx
fix oasis-engine/oasis-engine.github.io#368
> fix: remapping url when image is in url

- playground/pbr-clearcoat.ts
> feat: add clearcoat demo

- src/pages/gltf-viewer.tsx
> feat: support editing direct light separately

- playground/draw-lines.ts
增加一个三维世界内画线条的示例：
- 可以绘制线段，控制线段粗细，圆润程度，绘制的深度，绘制的延迟和线条的颜色。
- 绘制完后可以从各个角度观察。
- 涉及 ModelMesh，相机屏幕空间到三维空间转换，简单的自定义材质（双面剔除），PointerManager 的应用，绘制与特定向量垂直的矩形网格和圆形网格
> Playground: drawLines

- playground/animation-event.ts
- playground/animation-stateMachineScript.ts
- playground/skeleton-animation-additive.ts
- playground/skeleton-animation-play.ts
feat: opt animator playground code
> feat: opt animator playground code

- playground/sprite-slice.ts
> Playground: add sprite slice.

- docs/custom-material.md
- docs/custom-material.zh-CN.md
- docs/gltf.md
- docs/gltf.zh-CN.md
- docs/model.md
- docs/model.zh-CN.md
- docs/texture-compression.md
- docs/texture-compression.zh-CN.md
- docs/texture.md
- docs/texture.zh-CN.md
- playground/compressed-texture.ts
> docs: material && texture && gltf

- docs/input.md
- docs/input.zh-CN.md
- docs/sprite-renderer.md
- docs/sprite-renderer.zh-CN.md
- docs/sprite.md
- docs/sprite.zh-CN.md
- playground/sprite-slice.ts
> Doc: Sprite & SpriteRenderer

- docs/camera.md
- docs/camera.zh-CN.md
- 开篇先介绍透视投影和正交投影的使用和属性含义
- 相机的朝向和 lookat 函数
- 相机的渲染剔除（cullMask 和 Layer，需要描述 Layer 在层级中的影响关系和先后顺序）
- 单相机多次渲染 和 多相机渲染（单相机多次渲染主要讲onBeginRender 与 renderTarget，多相机主要讲CameraClearFlags，以及两者的性能差异）
> Doc:update camera doc

- playground/input-pointer.ts
> fix: input bug

- playground/.dev/vite.config.js
- playground/planar-shadow.ts
- playground/sprite-material-glitch-rgbSplit.ts
- Update planar shadow example
- Adapter to latest dev/0.9
> Update planar shadow example

- playground/animation-customAnimationClip.ts
- playground/animation-event.ts
- playground/animation-stateMachineScript.ts
- playground/skeleton-animation-additive.ts
- playground/skeleton-animation-crossfade.ts
- playground/skeleton-animation-play.ts
link: https://github.com/oasis-engine/oasis-engine.github.io/issues/474
> Add custom animationClip demo and opt animation demo

- src/components/doc/components/DocDetail.tsx
- src/components/doc/plugins/link.ts
Change list:
fix the routing to documentations on the Chinese Doc page
> fix: routings within the Chinese Documentation page

- src/components/Api/components/Item.tsx
This change fix the bug that cannot display class detail on APi page.
> fix: api page for Classes

- docs/resource-manager.md
- docs/resource-manager.zh-CN.md
> Add texture params docs

- src/components/header/index.less
vertical center search box; adjust search box width
> fix: adjust search box styles

- src/components/header/components/SearchBox.tsx
- src/components/header/index.less
> fix: search result style

- src/components/Api/util/apiUtil.ts
- src/components/doc/util/docUtil.ts
- src/components/header/headerUtils.ts
- src/siteconfig.json
change list:
update server info in siteConfig.json
> chore: update server address configs

- src/components/header/index.less
- src/components/header/index.tsx
> refactor: header layout

- docs/animator.md
- docs/animator.zh-CN.md
- docs/sprite-mask.md
> fix: update title

- docs/mesh.md
- docs/mesh.zh-CN.md
- docs/model-mesh.md
- docs/model-mesh.zh-CN.md
- src/components/Playground/index.less
> fix: code highlight typo

- docs/script.md
- docs/script.zh-CN.md
> Fix component life cycle error

- src/components/Examples/index.tsx
- src/components/Playground/index.less
- src/components/doc/components/DocMenu.tsx
- src/components/doc/index.tsx
- src/routes.tsx
- fix：文档页面菜单不固定的 bug
- fix：示例页面搜索 bug
> fix: some bugs

- src/components/Examples/index.tsx
- src/components/header/components/DocSearchRes.tsx
- src/components/header/components/ExampleSearchRes.tsx
update url when switching languages
> final touch

- src/components/home/Banner.tsx
- src/components/home/Features.tsx
- src/siteconfig.json
1,fix link on home page
2, use pre-prod server temporarily
> fix: links on home page

- README.md
- src/components/Api/index.tsx
- src/components/doc/components/DocDetail.tsx
> Fix: api links

- src/siteconfig.json
Change to the fixed server url of local and dev.
> fix: server config url

- src/App.tsx
- src/components/Api/components/Item.tsx
- src/components/Api/components/Kind.tsx
- src/components/Api/components/Menu.tsx
- src/components/Api/components/Package.tsx
- src/components/Api/index.tsx
- src/components/Loading/index.tsx
- src/components/header/components/NavigationMenu.tsx
- src/routes.tsx
- fix API page routes bug.
- refactor API page code make logic and JSX more readable.
- fix some style problems.
> fix: API page problems

- docs/install.md
- docs/install.zh-CN.md
- src/components/doc/components/DocDetail.tsx
- Add first mermaid diagram.
- Make the doc `max-width` wider.
- Format code.
> First mermaid

- docs/editor-menu.zh-CN.md
> Refactor: add editor menu doc(cn)

- labels.json
- src/components/Examples/index.tsx
- src/components/doc/components/DocDetail.tsx
- src/components/doc/index.tsx
- src/components/doc/util/docUtil.ts
- Add `doc-engine`, `doc-editor`, `doc-art` tags to differentiate doc menus.
- Change `ts` tag to `example`.
> Update menu tag

- docs/editor-animationClip.md
- docs/editor-animationClip.zh-CN.md
- docs/editor-animator.md
- docs/editor-animator.zh-CN.md
https://github.com/ant-galaxy/oasis-engine.github.io/issues/595
> feat: 增加AnimationClip编辑器文档

- docs/editor-mesh-renderer.md
- docs/editor-mesh-renderer.zh-CN.md
> doc: mesh renderer

- docs/editor-assets-panel.md
- docs/editor-assets-panel.zh-CN.md
> Add asset panel doc

- docs/editor-script-communication.zh-CN.md
- docs/editor-script.zh-CN.md
> feat: editor script doc

- docs/editor-camera.md
- docs/editor-camera.zh-CN.md
Fix #596 
Add the doc of editor camera component.
> Add Camera Component Doc

- docs/input.md
- docs/input.zh-CN.md
> Fix pointer doc error

- docs/cube.md
- docs/cube.zh-CN.md
> Fix: link error

- docs/cube.md
- docs/cube.zh-CN.md
- docs/engine.zh-CN.md
> fix: engine doc error

- src/components/doc/index.tsx
fix: https://github.com/ant-galaxy/oasis-engine.github.io/issues/642
> fix: layout style

- docs/particle-renderer.md
fix: https://github.com/ant-galaxy/oasis-engine.github.io/issues/643
> fix: particle doc

- playground/scene-fog.ts
> Add fog example

- playground/mrt.ts
demo中使用了RenderTarget自带的DepthTexture，[webgl2 深度图bug](https://github.com/ant-galaxy/oasis-engine/issues/1379) 需要修复后才能发布
> Add MRT Demo

- playground/AStar.ts
> feat: Astar

- playground/bounding-box.ts
> Add playground about bounging box

- playground/device-restore.ts
- playground/sprite-drawMode.ts
> Add device restore example

- playground/gizmo.ts
> fix: update gizmo example to adapt new api

- docs/editor-2d-spriteAtlas.zh-CN.md
- 介绍
- 使用
- 增
- 删
- 改
- 设置
- 最佳实践
>  Add editor atlas documentation

- src/App.tsx
- src/components/header/components/ScrollToTop.tsx
- src/components/header/index.tsx
当路由变化时，文档滚动到页头，解决用户查看文档之后切换文档，文档不是页头的 case
> feat: add scroll to top when route change

- docs/miniprogram.md
- docs/miniprogram.zh-CN.md
galacean 的 pointer 接受：
- pointerdown
- pointermove
- pointerup
- pointerleave
- pointercancel
因此在将 touch 转换为 pointer 时：
- touchstart 对应 pointerdown
- touchmove 对应 pointermove
- touchup 对应 pointerup pointerleave
- touchcancel 对应 pointercancel
link https://github.com/galacean/miniprogram-adapter/pull/17
> Update miniprogame adapter doc

- src/components/Playground/index.tsx
- src/components/doc/components/DocDetail.tsx
fix: 
- https://github.com/galacean/galacean.github.io/issues/755
> fix: playground not load

- docs/canvas.md
- docs/canvas.zh-CN.md
- docs/engine.md
- docs/engine.zh-CN.md
> fix: doc error

- api/design.json
- api/draco.json
- api/math.json
- api/physics-lite.json
- api/physics-physx.json
- api/rhi-webgl.json
- api/shader-lab.json
update version 1.1 engine api doc
> feat: update v1.1 engine api

- playground/camera-depth-texture.ts
- playground/scene-fog.ts
> Add camera depth texture playground

- playground/framebuffer-picker.ts
1. use PBR material
2. add region pick selection
> Feat: add region pick for framebuffer picker

- playground/outline-postprocess.ts
update outline to include children entities with another color.
> fix: update outline to include children

- playground/box-selection.ts
Create demo for https://github.com/galacean/engine-toolkit/pull/216
> Add box selection demo

- docs/editor.zh-CN.md
> refactor: editor doc

- docs/particle-renderer.md
- docs/particle-renderer.zh-CN.md
Use table style instead of list
> refactor: particle doc

- api/design.json
- api/draco.json
- api/loader.json
- api/math.json
- api/physics-lite.json
- api/physics-physx.json
- api/rhi-webgl.json
- api/shader-lab.json
- docs/shader-lab.md
> fix: apidoc

- src/components/Api/index.tsx
- src/components/Examples/index.tsx
- src/components/contextProvider/index.tsx
- src/components/doc/components/DocDetail.tsx
- src/components/doc/index.tsx
- fix: https://github.com/galacean/galacean.github.io/issues/836  (including doc/example/API pages, have the same problem.)
- fix: markdown `quoteblock` hidden bug and add some styles.
> fix redirect and blockquote bugs

- playground/pbr-anisotropy.ts
> [Playground] PBR Anisotropy

- docs/core-engine.zh-CN.md
- docs/interface-assets.zh-CN.md
- docs/interface-inspector.zh-CN.md
- docs/interface-menu.zh-CN.md
- docs/interface-shortcut.zh-CN.md
> Refactor: update interface doc

- src/components/Playground/index.tsx
- src/components/doc/components/DocDetail.tsx
- src/components/home/Production.tsx
- src/components/home/index.tsx
- fix: imge width in doc
- fix: code action version
- refactor: remove logo in homepage
> Small bugfix

- docs/core-scene.zh-CN.md
> Update scene doc

- docs/input-keyboard.zh-CN.md
- docs/input-pointer.zh-CN.md
- docs/input-wheel.zh-CN.md
- docs/input.zh-CN.md
- playground/input-pointerButton.ts
- playground/input-pointerRaycast.ts
- playground/input-wheel.ts
> 【文档更新】更新交互文档

- playground/camera-depth-texture.ts
- playground/mrt.ts
- playground/screenshot.ts
- playground/transparent-shadow.ts
adapter 1.2 api change from https://github.com/galacean/runtime/pull/1997
> Adapter 1.2 api change of flipY

- playground/material-head-distort.ts
> Add heat distort example

- playground/transparent-shadow.ts
> Playground add transparent shadow
